server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smartflow-task
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: true
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer